[tool.poetry]
name = "meshtastic_link_planner"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "GNU GPLv3"
readme = "README.md"

[tool.poetry.scripts]
start = "meshtastic_link_planner.main:start"


[tool.poetry.dependencies]
python = "<3.14,>=3.10"
affine = "2.4.0"
amqp = "5.3.1"
annotated-types = "0.7.0"
anyio = "4.6.2.post1"
attrs = "24.2.0"
billiard = "4.2.1"
boto3 = "1.35.68"
botocore = "1.35.68"
celery = "5.4.0"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
click = "8.1.7"
click-didyoumean = "0.3.1"
click-plugins = "1.1.1"
click-repl = "0.3.0"
cligj = "0.7.2"
contourpy = "1.3.1"
cycler = "0.12.1"
diskcache = "5.6.3"
fastapi = "0.115.0"
fonttools = "4.55.0"
geojson = "3.1.0"
h11 = "0.14.0"
h3 = "4.1.2"
haversine = "2.8.1"
idna = "3.10"
jmespath = "1.0.1"
joblib = "1.4.2"
kiwisolver = "1.4.7"
kombu = "5.4.2"
matplotlib = "3.9.2"
numpy = "2.1.3"
packaging = "24.2"
pillow = "11.0.0"
prompt_toolkit = "3.0.48"
psycopg2-binary = "2.9.10"
pydantic = "2.9.2"
pydantic_core = "2.23.4"
pyparsing = "3.2.0"
python-dateutil = "2.9.0.post0"
PyYAML = "6.0.2"
rasterio = "1.4.2"
redis = "5.2.0"
requests = "2.32.3"
s3transfer = "0.10.4"
scipy = "1.14.1"
six = "1.16.0"
sniffio = "1.3.1"
SQLAlchemy = "2.0.36"
starlette = "0.38.6"
typing_extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
uvicorn = "0.30.6"
vine = "5.1.0"
wcwidth = "0.2.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
